### ISSUE TITLE
Contract Verification

### ISSUE THREAD

**Issue by snow-farmer** [yieldyak/smart-contracts#1]
# Background

We reach an error verifying contracts on Avalanche Explorer.

# Steps to reproduce

This example uses `DexStrategyV4.sol` for `0xA544b965C2a05b97C44f3126cec916332aFb3175`.

1. Compile and flatten contract

```
npx hardhat flatten contracts/strategies/DexStrategyV4.sol > DexStrategyV4.sol
```

2. Remove all duplicate license and pragma lines from flattened file.
3. Visit [contract verification page](https://cchain.explorer.avax.network/address/0xA544b965C2a05b97C44f3126cec916332aFb3175/verify-via-flattened-code/new)
4. Fill out details using the [solcInputs](https://github.com/yieldyak/smart-contracts/blob/master/deployments/mainnet/solcInputs/b8a898362a0bdb708a3e4d53fc8e12d2.json) from [deployments file](https://github.com/yieldyak/smart-contracts/blob/master/deployments/mainnet/PGL-AVAX-PNG_v3.json).

```
Contract name: DexStrategyV4
Compiler: v0.7.3
Optimization: Yes
Runs: 200
```

# Expected result

Contract is verified [here](https://cchain.explorer.avax.network/address/0xA544b965C2a05b97C44f3126cec916332aFb3175/contracts)

# Actual result

Error message:

```
There was an error compiling your contract: The "chainid" instruction is only available for Istanbul-compatible VMs (you are currently compiling for "byzantium").
```

**Comment by snow-farmer** [comment]
Update:
* One contract was successfully [verified](https://cchain.explorer.avax.network/address/0x4DD36b27e038E5c479d8BEC440c8f4eE89B6dF5D/contracts) - note: optimization is disabled
* Other contracts have [slightly mismatched bytecode](https://www.diffchecker.com/GNZJhlMb) - note: optimization is enabled
* We no longer receive the error message for "Chain ID" by switching EVM Version to default. However, we still receive error `Connection lost`

**Comment by ASlowCheetah** [comment]
In regards to the issue, we did reverse engineer the issue and there was many problems at play, I spent some time together with two other community members, and Avalabs troubleshooting the issue, here are key takeaways:

1. Blockscout sometimes parsers comments, so we should avoid commenting codelines, instead, stick to use only verbal comments.
2. ABIEncoderV2 is experimental and should be avoided whenever possible as it can lead to issues with flatten files, as the experimental encoder definition leaks to other classes
3. Always deploy to FUJI(testnet) and verify the contract there first, it's a good indicative that if it doesn't verify, we should fix this issue before deploying on mainnet.
4. Deploying from flatten file can be a good idea to avoid bytecode mismatching from separated files to the flatten ones, this makes the process easier
5. Supplying the ABI constructor to the blockscout sometimes is the answer, to identify the ABI constructor you can look into the transaction that deployed the contract, in the Trace tab, you'll see a json, you're looking into the end of the field 'init'. 43 + compiler version(00073) + 0033 is the bytecode that you're looking at the end, everything after this bytecode sequence is the constructor.
