### ISSUE TITLE
How do I access the ABI?

### ISSUE THREAD

**Issue by j4ckcyw** [yieldyak/smart-contracts#14]
I would like to be able to write a script that calls FarmData on a farm. I had tried to import farm-data.js and call it there. It complains artifacts are not deployed, because the abi path is relative. How do I access its ABI?

Can you provide an option like how pangolin does to access the ABI?
https://github.com/pangolindex/exchange-contracts#accessing-the-abi

**Comment by snow-farmer** [comment]
abis are automatically generated. try running

```
npx hardhat compile
```

**Comment by j4ckcyw** [comment]
Sure. Then how do I depend on yieldyak as a node_modules? This would require me to work within yieldyak git repo, right?

**Comment by snow-farmer** [comment]
You can use the abi that is generated (json file) without further dependancy on the repo.

All contract addresses and abis are also available from the `deployments` folder.
