### ISSUE TITLE
Elk ILP Support

### ISSUE THREAD

**Issue by snow-farmer** [yieldyak/smart-contracts#7]
Elk pools pay ILP (impermanent loss protection) on withdraw. New strategy to `reinvest` should claim any pending ILP. We should consider an additional `reinvest` in the `withdraw` flow. The goal is to pay YY depositors their "fair share" of the ILP.

**Comment by tbrunain** [comment]
I created [this PR ](https://github.com/yieldyak/smart-contracts/pull/24) for this issue . Feedback welcome : )
